Feature album management
leit-uchile/memoriafotografica pull request #15
Opened 2020-11-07 15:29 UTC by dcaceresm

Está pendiente el merge con los últimos cambios desde `dev`

2020-11-07 16:25 UTC, dario617 commented on backend/Gallery/api.py
> +            if request.user.is_anonymous or request.user.user_type == 1: aPhoto['metadata'] = list(filter(lambda x: check_approval(x), aPhoto['metadata']))
Esto compila en Python?

2020-11-07 16:27 UTC, dario617 commented on frontend/src/components/PhotoEditor.jsx
> +PhotoEditor.propTypes = {
Like

2020-11-07 16:29 UTC, dario617 commented on frontend/src/pages/User/AlbumCollection/AlbumView.jsx
> +  const DeleteAlbumModal = (props) => {
No se si hay un problema de performance al definir el componente dentro de otro componente, yo lo sacaria afuera

2020-11-07 16:30 UTC, dario617 commented on frontend/src/pages/User/AlbumCollection/AlbumView.jsx
>    useEffect(() => {
No me parece que haga algo este useEffect

2020-11-07 16:32 UTC, dario617 commented on frontend/src/pages/User/AlbumCollection/AlbumView.jsx
> +    if(editAlbumStatus.sent && editAlbumStatus.success) setAction(true)
Sugiero agregar // eslint-disable-next-line para eliminar el error de consola de setAction should be on the dependecy tree

2020-11-07 16:40 UTC, dario617 commented on frontend/src/pages/User/AlbumCollection/AlbumView.jsx
> +        p.selected = !p.selected
Esto no modifical el original cierto?

2020-11-07 16:47 UTC, dario617 commented on frontend/src/pages/User/AlbumCollection/AlbumView.jsx
>  const mapActionsToProps = (dispatch) => ({
Aca cambialo a bindActionCreators, la idea de esto es que simplifica la sintaxis (originalmente no es su proposito). En este caso tendras que igual hacer explicitas algunos argumentos:
`
const mapActionsToProps = (dispatch) => bindActionCreators({
  loadInfo: gallery.album.loadAlbumInfo,
  pushPhotos: site_misc.pushPhotoArray,
  setIndex: site_misc.setSelectedId,
  onLoadGetPhotos: user.getUserPhotos,
  deleteAlbum: gallery.album.deleteAlbum,
  editAlbum: gallery.album.editAlbum
},dispatch)
`
Cuando llames a loadInfo en el componente tendras que explicitar el segundo argumento

2020-11-07 16:49 UTC, dario617 commented on frontend/src/pages/User/PhotoCollection/CreateAlbumModal.jsx
> +  const mapActionsToProps = (dispatch) => ({
Aca tambien lo de bindActionCreators, aun cuando sea overkill. Se importa directamente de redux

2020-11-07 16:50 UTC, dario617 commented on frontend/src/reducers/gallery/albumcollection.js
> +    case DELETE_ALBUM_SENT:
Solo una duda, alguien reinicia estas flags al cambiar de vista?

2020-11-07 16:51 UTC, dario617 requested changes
Revision :+1:

2020-11-14 13:51 UTC, dcaceresm commented on backend/Gallery/api.py
> +            if request.user.is_anonymous or request.user.user_type == 1: aPhoto['metadata'] = list(filter(lambda x: check_approval(x), aPhoto['metadata']))
lo dices por la sintax `obj.attr` ? deberia porque son objetos de python :thinking:

2020-11-14 13:52 UTC, dario617 commented on backend/Gallery/api.py
> +            if request.user.is_anonymous or request.user.user_type == 1: aPhoto['metadata'] = list(filter(lambda x: check_approval(x), aPhoto['metadata']))
Por el one line digo

2020-12-07 13:58 UTC, dario617 approved these changes

2020-12-07 14:54 UTC, merged