Feature dashboard usuario
leit-uchile/memoriafotografica pull request #20
Opened 2020-12-13 12:27 UTC by IsaiasVenegas

Might be merge conflicts between EditPhotosModal versions

2020-12-13 14:17 UTC, dario617 commented on frontend/src/css/App.css
> +.dashboard-col {
¿Por que el cambio? La gracia del original es declarar una sola vez la clase dashboard y luego aprovechar que se declaran solas .col con reactstrap

2020-12-13 14:18 UTC, dario617 commented on frontend/src/pages/Curador/Landing.jsx
> +        <Col className="dashboard-col">
Continuacion de punto anterior: evitamos escribir la nueva clase.

2020-12-13 14:20 UTC, dario617 commented on frontend/src/pages/User/AlbumCollection/UserAlbums.jsx
> +        <Col className="dashboard-col">
.

2020-12-13 14:24 UTC, dario617 commented on frontend/src/pages/User/Landing.jsx
> +          <Col className="dashboard-col">
.

2020-12-13 14:26 UTC, dario617 commented on frontend/src/pages/User/PhotoCollection/UserPhotos.jsx
> +          <Col className="dashboard-col">
.

2020-12-13 14:27 UTC, dario617 commented on frontend/src/pages/User/PhotoCollection/UserPhotos2.jsx
> +        <Col className="dashboard-col">
.

2020-12-13 14:29 UTC, dario617 commented on frontend/src/pages/User/Profile/EditProfile.jsx
> +          <Col className="dashboard-col">
.

2020-12-13 14:30 UTC, dario617 commented on frontend/src/pages/User/Profile/PublicProfile.jsx
> -const PublicProfile = ({
¿Alguna razón particular para dejarlo como clase?

2020-12-13 14:32 UTC, dario617 commented on frontend/src/pages/User/Profile/PublicProfile2.jsx
> +const PublicProfile = ({
Ah! nos quedamos con la version 1 o 2?

2020-12-13 14:35 UTC, dario617 commented on frontend/src/pages/User/PhotoCollection/UserPhotos2.jsx
> +              {photos.results ? (
photos.results siempre existe, entonces ¿el spinner se muestra en algún caso?

2020-12-13 14:35 UTC, dario617 requested changes
Inbox a Telegram si tienes dudas

2020-12-13 18:10 UTC, IsaiasVenegas commented on frontend/src/css/App.css
> +.dashboard-col {
El problema es que cada Col anidada dentro de otra Col obtiene padding, lo que hace cajas y cajas

2020-12-13 18:17 UTC, IsaiasVenegas commented on frontend/src/pages/User/PhotoCollection/UserPhotos2.jsx
> +              {photos.results ? (
Este componente falta por actualizar para que replique el funcionamiento de las herramientas del curador. La idea es que photos inicie como objeto vacio y que luego de solicitar los datos al back este se setea.

2020-12-13 18:18 UTC, IsaiasVenegas commented on frontend/src/pages/User/Profile/PublicProfile.jsx
> -const PublicProfile = ({
Solo para crear una versión v2 del archivo, conservando la clase y la nueva versión funcional

2020-12-13 18:18 UTC, IsaiasVenegas commented on frontend/src/pages/User/Profile/PublicProfile2.jsx
> +const PublicProfile = ({
Nos quedamos con la version 2. La version 1 era solo en caso de necesitarla

2020-12-13 20:43 UTC, IsaiasVenegas commented on frontend/src/css/App.css
> +.dashboard-col {
Probablemente sea bueno aplicar otro selector css y desechar este cambio

2020-12-14 20:16 UTC, IsaiasVenegas commented
Revertido el cambio en el css. En el próximo commit probaré con un nuevo selector

2020-12-14 21:53 UTC, dario617 approved these changes

2020-12-14 21:53 UTC, merged