Feature upload refactor
leit-uchile/memoriafotografica pull request #31
Opened 2021-06-05 16:42 UTC by JoaquinDiazTapia

2021-06-12 14:54 UTC, dario617 commented on backend/Gallery/auth.py
> +                _('User is not a guest.'))
Esto esta bien? yo digo el **_** asumo que es de traduccion pero no veo el import

2021-06-12 15:14 UTC, dario617 commented on backend/Users/endpoints.py
> +        include('django_rest_passwordreset.urls', namespace='password_reset')),
URL duplicada

2021-06-12 15:15 UTC, dario617 commented on backend/Users/models.py
> +    completed_registration = models.BooleanField(_('completed_registration'), default=True)
Este valor por defecto es correcto?

2021-06-12 15:17 UTC, dario617 commented on backend/WebAdmin/views.py
> +        data = 'http://memoriafotografica.cl/confirm/?code=' + attached  #code
Esto no es parte del commit pero seria bueno agregarlo:

- Agregar un campo en los settings con la URL del dominio.
- Cargar ese valor desde los settings aqui para reemplazar los memoriafotografica

En el fondo para que sea mantenible

2021-06-12 15:20 UTC, dario617 commented on frontend/src/actions/gallery_api/photos.js
> +      Authorization: "Token " + token,
Y si haces en una linea
`let header = token !== null ? {Authorization: "Token " + getState().user.token} : {Authorization: "Token " + token}`

2021-06-12 15:21 UTC, dario617 commented on frontend/src/actions/metadata_api.js
> +  if (token) {
aqui tambien

2021-06-12 15:29 UTC, dario617 commented on frontend/src/actions/webadmin_api.js
> +      // else {
Falta ver el caso de respuestas fallidas

2021-06-12 15:30 UTC, dario617 commented on frontend/src/components/TermsOfUse/FormTermsOfUse.jsx
> +export default function FormTermsOfUse({
De ser posible agrega los proptypes

2021-06-12 15:31 UTC, dario617 commented on frontend/src/components/TermsOfUse/TermsOfUseModal.jsx
> +const TermsOfUseModal = ({
Tambien proptypes

2021-06-12 15:48 UTC, dario617 commented on frontend/src/pages/Register/CompleteRegistration.jsx
> +import { useHistory } from "react-router-dom";
No se usa?

2021-06-12 15:49 UTC, dario617 commented on frontend/src/pages/Register/CompleteRegistrationMessage.jsx
> +import { useHistory } from "react-router-dom";
se usa?

2021-06-12 15:52 UTC, dario617 commented on frontend/src/pages/Upload/Steps/UploadUnregister.jsx
> +              <FormGroup check>
Conviertelo en un select

2021-06-12 15:55 UTC, dario617 commented on frontend/src/reducers/user.js
> +  resendActivation:'',
ponle al resendActivation un estado 'idle' inicial, como se hará en el resto del codigo

2021-06-12 15:55 UTC, dario617 commented on frontend/src/reducers/user.js
> +      return { ...state , resendActivation:''}
aqui tambien

2021-06-12 15:56 UTC, dario617 commented on frontend/src/reducers/webadmin.js
> +  guestState: false,
completeRegistration no esta en el init. Es intencional?

2021-06-12 15:57 UTC, dario617 requested changes
Comentarios iniciales

2021-06-12 16:02 UTC, dario617 commented on backend/Gallery/auth.py
> +                _('User is not a guest.'))
al parecer no es necesario 🤷🏻

2021-06-12 17:03 UTC, JoaquinDiazTapia commented on backend/Users/models.py
> +    completed_registration = models.BooleanField(_('completed_registration'), default=True)
Segun yo si, el flujo "normal" para registrar un usuario es a traves de registrarse, me hace sentido dejarlo True, y solo sobreescrirlo false cuando se crea un invitado.

2021-07-24 19:03 UTC, dario617 commented
Falta completar tests para Recaptcha y token de validacion. Se separa en tarea independiente

2021-07-24 19:03 UTC, merged